version: "2"
services:
  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_CREATE_TOPICS: "steaph.environments:1:1,steaph.schedules:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:                                                                                                                                                                                                
      - /var/run/docker.sock:/var/run/docker.sock
  steaph-api:
    build: ./../steaph-api/
    ports:
      - "8080:8080"
    links:
      - mongo
      - kafka
  steaph-module-connector:
    build: ./../steaph-module-connector/
    links:
      - kafka
    depends_on:
      - steaph-api
